### ISSUE TITLE
Vfat wtf?

### ISSUE THREAD

**Issue by Haxerall** [OpenIPC/website#21]
В инструкции по прошивке с флешки написано отформатируйте флешку в VFAT. 👍 Наверное уже никто и не знает что это такое может надо написать FAT32 и не пугать людей народ не одупляет что делать. 😂

**Comment by themactep** [comment]
где именно это написано? ссылка на страницу ускорит решение.

**Comment by themactep** [comment]
done.

**Comment by Haxerall** [comment]
https://openipc.org/cameras/vendors/hisilicon/socs/hi3518ev100
Спасибо. Исправлено

**Comment by Haxerall** [comment]
https://github.com/OpenIPC/device-mjsxj02hl

**Comment by themactep** [comment]
это не имеет отношения к сайту.
