### ISSUE TITLE
Mention of premium account on telegram

### ISSUE THREAD

**Issue by FlyRouter** [OpenIPC/website#23]
Hi Paul !

When you get a chance, please add the information about enabling premium account in telegram on the page where we have all the links to the chat group.
I think a good option would be to mention also the option of click-to-transfer, for those who can't or don't want to use premium. 
And also to write that in any group, which does not have a language priority, you can and should write in what you can.

And one more small request - please remove (RU) from the FPV group, it has long been international and there often write in a mix of languages.

Thank you very much !

**Comment by themactep** [comment]
Done
