### ISSUE TITLE
Collection of wishes and recommendations on the OpenWall page

### ISSUE THREAD

**Issue by ZigFisher** [OpenIPC/website#5]

**Comment by ZigFisher** [comment]
Display the operating time of the device in days, hours and minutes. 
The current display is misleading and looks like just showing the time.

**Comment by ZigFisher** [comment]
Add a description string of a small fixed length where you can specify a description for the photo. 
This description must be taken from the plugin settings on the device.

**Comment by ZigFisher** [comment]
On the start page, display only one latest picture from each camera. 
If there is no data from the camera for more than an hour, hide it from the wall or place it at the very end of the list

**Comment by ZigFisher** [comment]
Make it possible to sort and select by the same processor and sensor from the total amount of data

**Comment by ZigFisher** [comment]
Align and make uniform sizes of tiles for different cameras (images vary in size)

**Comment by themactep** [comment]
this one issue for all requests format is a hassle. i close this one. please open new requests one task per issue. thank you.
