### ISSUE TITLE
Ошибки при выборе NAND памяти в генераторе инструкций

### ISSUE THREAD

**Issue by saymonnet1** [OpenIPC/website#9]
Если выбрать [на странице процессора HiSilicon HI3516EV300](https://openipc.org/cameras/vendors/hisilicon/socs/hi3516ev300) тип памяти NAND и версию Ultimate, то есть несколько несоответствий:
1. В инструкции по прошивке u-boot вместо **sf erase**, **sf write** должны стоять команды **nand erase** и **nand write**. Какую команду вводить вместо **sf probe 0** я так и не понял - делал без неё.
2. Ссылка на загрузку OpenIPC Linux Ultimate ведет к файлу **openipc.hi3516ev300-ultimate-br.tgz**, а должна вести к файлу  **openipc.hi3516ev300-nand-br.tgz** - 
3. В архиве **openipc.hi3516ev300-nand-br.tgz** 2 файла rootfs: ubi и ubifs. Прошивка идет из первого файла, для чего второй не очень понятно.

**Comment by ZigFisher** [comment]
_Ссылка на загрузку OpenIPC Linux Ultimate ведет к файлу openipc.hi3516ev300-ultimate-br.tgz, а должна вести к файлу openipc.hi3516ev300-nand-br.tgz_

Тут не соглашусь..
Если у вас тип флешки NAND то вы её должны выбрать, а если выбрали, то в списке прошивок под NAND должна быть доступна только ссылка на openipc.hi3516ev300-nand-br.tgz  а не три типа lite/ultimate/fpv как сейчас.
Именно этот нюанс я и просил написать сюда, что-бы @themactep обновил алгоритм

В сухом остатке, 
если пользователь выбирает NOR то если 8 метров, может выбрать только lite, если 16 и более то весь набор lite/ultimate/fpv
если пользователь выбрал NAND, то должна быть ссылка на nand версию прошивки, которая, которая, если я правильно помню, является копией ultimate, только с модифицированным ядром и собственно упакованной в ubi файловой системой.

По вопросу 1 у нас генератор на сайте пишет что в разработке опция, напишите пожалуйста где вы это нашли, подправим. так-же неплохо было-бы получить от вас полный листинг команд которые заработали в итоге. Команду sf probe 0 которая просто указывает что флешку нужно инициализировать, наверное по аналогии нужно искать при вызове nand, возможно что-то подскажет по этому поводу @dimerr а так-же он сможет подсказать и по вопросу 3

**Comment by themactep** [comment]
сейчас при выборе типа памяти nand предлагается единственный вариант прошивки ultimate. что касается комманд - проверьте их правильность для nand в генерируемой инструкции, и если они рабочие - тикет наверное можно закрыть.

**Comment by saymonnet1** [comment]
> сейчас при выборе типа памяти nand предлагается единственный вариант прошивки ultimate. что касается комманд - проверьте их правильность для nand в генерируемой инструкции, и если они рабочие - тикет наверное можно закрыть.

Проверил первый пункт. 
Команды для прошивки u-boot так и не изменились. Генерятся sf erase и т.д. а должны генерить nand erase.

**Comment by themactep** [comment]
поменял везде, где увидел. пожалуйста, проверь еще раз сейчас.

**Comment by themactep** [comment]
поскольку жалоб не, считаю тикет коцнутым.
